### PR TITLE
Fix watcher bug (incorrect fdset when watching with select)

### PR DESCRIPTION
**Pull request by olb17**
Fixing issue #1

### CODE REVIEW

**Comment by brian-armstrong** [comment]
Thanks for the PR.

It's weird, I vaguely remember looking into this issue, and even writing code similar to this. I even thought I had committed it, but I can't find any trace of that, so maybe I just imagined I did. Thanks for the fix!

**Comment by brian-armstrong** [comment]
Also, for my own edification, did this just affect FDs greater than 63?

**Comment by olb17** [comment]
This affected all fd where 2^fd >= 64 .
So fd >= 6.
The watcher only worked for fd 3 4 or 5 (considering 0 1 & 2 are already
used for stdin stdout and stderr).
In my case, it failed for fd == 9.

Le 16 janv. 2018 1:58 AM, "Brian Armstrong" <notifications@github.com> a
écrit :

**Comment by brian-armstrong** [comment]
Yikes, that's quite a lot more broken than I realized. Thanks for the PR!

**Pull request merged**
